import loadable from 'loadable-components';

export const Button = loadable(() => import('components/Button'));
export const Container = loadable(() => import('components/Container'));
export const Error = loadable(() => import('components/Error'));
export const Footer = loadable(() => import('components/Footer'));
export const Header = loadable(() => import('components/Header'));
export const Input = loadable(() => import('components/Input'));
export const Label = loadable(() => import('components/Label'));
export const LoginForm = loadable(() => import('components/LoginForm'));
export const Logo = loadable(() => import('components/Logo'));
export const Main = loadable(() => import('components/Main'));
export const Menu = loadable(() => import('components/Menu'));
export const MenuIcon = loadable(() => import('components/MenuIcon'));
export const OctIcon = loadable(() => import('components/OctIcon'));
export const StackList = loadable(() => import('components/StackList'));
export const SubTitle = loadable(() => import('components/SubTitle'));
export const Title = loadable(() => import('components/Title'));
export const User = loadable(() => import('components/User'));
export const UserList = loadable(() => import('components/UserList'));
